---
# All servers
- hosts: "tag_aws_cloudformation_stack_name_infra"
  user: ubuntu
  gather_facts: True
  become: yes
  roles:
    - common
# Demo server
- hosts: tag_Name_Demo
  user: ubuntu
  become: yes
  roles:
    - demo

# Orders server
- hosts: tag_Name_Orders
  user: ubuntu
  become: yes
  roles:
    - orders

# Frontend server
- hosts: tag_Name_Frontend
  user: ubuntu
  become: yes
  roles:
    - frontend
    

# Stores server
- hosts: tag_Name_Stores
  user: ubuntu
  become: yes
  roles:
    - stores

# Auth server
- hosts: tag_Name_Auth
  user: ubuntu
  become: yes
  roles:
    - auth

# Products server
- hosts: tag_Name_Products
  user: ubuntu
  become: yes
  roles:
    - products
