---
# All servers
- hosts: "tag_aws_cloudformation_stack_name_infra"
  user: ubuntu
  gather_facts: True
  become: yes
  roles:
    - common
# Demo server
- hosts: tag_Name_Demo
  user: ubuntu
  become: yes
  roles:
    - demo

# Orders server
- hosts: tag_Name_Orders
  user: ubuntu
  become: yes
  roles:
    - orders
    
# Auth server
- hosts: tag_Name_Auth
  user: ubuntu
  become: yes
  roles:
    - auth
