---
# All servers
- hosts: "tag_aws_cloudformation_stack_name_infra"
  user: ubuntu
  gather_facts: True
  become: yes
  roles:
    - common

# Auth server
- hosts: tag_Name_Auth
  user: ubuntu
  become: yes
  roles:
    - Auth
