Resources:
  securityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Firewall rules
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
  securityGrouIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId: !GetAtt securityGroup.GroupId
      GroupId: !GetAtt securityGroup.GroupId

  demoInstance:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: ami-cec307b7
      InstanceType: "t2.small"
      KeyName: arcada
      SecurityGroups: 
        - Ref: securityGroup
      Tags: 
        - Key: Name
          Value: Demo

  authInstance:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: ami-cec307b7
      InstanceType: "t2.small"
      KeyName: arcada
      SecurityGroups: 
        - Ref: securityGroup
      Tags: 
        - Key: Name
          Value: Auth

  frontInstance:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: ami-cec307b7
      InstanceType: "t2.small"
      KeyName: arcada
      SecurityGroups: 
        - Ref: securityGroup
      Tags: 
        - Key: Name
          Value: Frontend