---
- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apache2
    - libapache2-mod-php

- name: Configure apache
  register: apache_conf
  copy:
    src: apache_vhost
    dest: /etc/apache2/sites-enabled/stores.conf

- name: Restart apache
  when: apache_conf.changed
  service:
    name: apache2
    state: restarted

- name: Start apache
  service:
    name: apache2
    state: started
    enabled: yes

- name: Set up authorized keys
  authorized_key:
    user: ubuntu
    state: present
    key: '{{ item }}'
  with_file:
    - stores_devops.pub

- name: Clone application repo
  git:
    repo: 'https://github.com/Arcada-Devops-2017/stores.git'
    dest: /var/www/stores

- name: Upload update script
  copy:
    src: update.sh
    dest: /home/ubuntu/update.sh
    owner: ubuntu
    group: ubuntu
    mode: 0700
