---
- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apache2

- name: Enable apache proxy modules
  register: apache_mods
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - proxy
    - proxy_http

- name: Configure apache
  register: apache_conf
  copy:
    src: apache_vhost
    dest: /etc/apache2/sites-enabled/stores.conf

- name: Restart apache
  when: apache_conf.changed or apache_mods.changed
  service:
    name: apache2
    state: restarted

- name: Start apache
  service:
    name: apache2
    state: started
    enabled: yes
