---
- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - mysql-client
    - apache2
    - libapache2-mod-php
    - php-mysql
    - python-pip
    - libmysqlclient-dev

- name: Install the Python MySQLB module
  pip: name=MySQL-python
    
- name: Copy the root credentials as .my.cnf file
  template: src=root.cnf.j2 dest=~/.my.cnf mode=0600

- name: Update MySQL root password for all root accounts
  register: root_password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_pass }}" 
    state: present
  with_items:
    - "{{ ansible_hostname }}"
    - "127.0.0.1"
    - "::1"
    - localhost

- name: Create a new database with name 'stores'
  mysql_db:
    name: stores
    state: present
    
- name: Stores data (sql)
  copy:
    src: data.sql
    dest: /home/ubuntu

- name: Copy database dump file
  register: databasedump
  copy:
    src: create.sql
    dest: /tmp
    
- name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
  when: databasedump.changed
  mysql_db:
    state: import
    name: stores
    target: /tmp/create.sql

- name: Setup app mysql user
  register: user_password
  mysql_user:
    name: stores
    host: "{{ item }}"
    priv: "stores.*:ALL" 
    password: "{{ mysql_user_pass }}"
    state: present
  with_items:
    - "127.0.0.1"
    - "localhost"

- name: Ensure Anonymous user(s) are not in the database
  register: anon_user
  mysql_user: 
    name: ''
    host: "{{ item }}"
    state: absent
  with_items:
    - localhost
    - "127.0.0.1"
    - "{{ ansible_hostname }}"

- name: Remove the test database
  register: test_db
  mysql_db:
    name: test
    state: absent

- name: Restart mysql
  when: root_password.changed or anon_user.changed or test_db.changed or user_password.changed
  service:
    name: mysql
    state: restarted

- name: Configure apache
  register: apache_conf
  copy:
    src: apache_vhost
    dest: /etc/apache2/sites-enabled/stores.conf

- name: Restart apache
  when: apache_conf.changed
  service:
    name: apache2
    state: restarted

- name: Start apache
  service:
    name: apache2
    state: started
    enabled: yes

- name: Set up authorized keys
  authorized_key:
    user: ubuntu
    state: present
    key: '{{ item }}'
  with_file:
    - stores_devops.pub

- name: Clone application repo
  git:
    repo: 'https://github.com/Arcada-Devops-2017/stores.git'
    dest: /var/www/stores

- name: Upload update script
  copy:
    src: update.sh
    dest: /home/ubuntu/update.sh
    owner: ubuntu
    group: ubuntu
    mode: 0700
