---
- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apache2
    - libapache2-mod-php

- name: Configure apache
  register: apache_conf
  copy:
    src: apache_vhost
    dest: /etc/apache2/sites-enabled/stores.conf

- name: Restart apache
  when: apache_conf.changed or apache_mods.changed
  service:
    name: apache2
    state: restarted

- name: Start apache
  service:
    name: apache2
    state: started
    enabled: yes

- name: Creates the /var/www/stores directory
  file:
    path: /var/www/stores
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
    recurse: yes

- name: Copy testfile
  copy: src=index.php dest=/var/www/stores/index.php mode=0664

- user:
    name: stores
    comment: "stores"
    uid: 8888

- name: Set up authorized keys
  authorized_key:
    user: stores
    state: present
    key: '{{ item }}'
  with_file:
    - ssh_key.pub

- name: Clone application repo
  git:
    repo: 'https://github.com/Arcada-Devops-2017/stores.git'
    dest: /var/www/stores
